services:
  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    environment:
      LLM_PROVIDER: "${LLM_PROVIDER}"      
      LLM_MODEL: "${LLM_MODEL}"
      GROQ_API_KEY: "${GROQ_API_KEY}"
      LLM_TEMPERATURE: "${LLM_TEMPERATURE}"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_USER: "${SMTP_USER}"
      SMTP_PASS: "${SMTP_PASS}"
      EMAIL_FROM: "${EMAIL_FROM}"
      EMAIL_MIN_INTERVAL: "${EMAIL_MIN_INTERVAL}"


  nginx:
    build: ./frontend
    ports:
      - "80:80"

volumes:
  mongo-data:


